### ISSUE TITLE
验证集和测试集相同？

### ISSUE THREAD

**Issue by crayonyon** [ACVAE/ACVAE-PyTorch#1]
你好，我读了你的代码，这里有点疑问：
在dataset_load.py 这个文件中，generate_test_data 和 generate_validate_data 这个两个function中都调用了 generate_index_data ，而传入的参数分别是 index = test_id, 和 index = valid_id,  valid_id和test_id其实相同（在该文件的line 128，129，130），于是经过调用 generate_index_data ，得到的验证集和测试集是一样的，请问我说的对吗？ 如果确实是这样，那测试集和验证集相同似乎不太合理吧？（个人看法，如果不对，请你给出指正，谢谢！）

**Comment by xiez22** [comment]
您好，确实是这样的。这样构建代码主要是为了通用性，把验证集的部分放进来，让代码能够适应更多的数据格式（这一部分代码实际中可以不需要）。我们对每个用户都是按照论文里提到的划分方式（8:2）划分train set和test set的，没有使用到验证集。
