### ISSUE TITLE
感觉很高端的工作

### ISSUE THREAD

**Issue by sizhongyibanhts** [ACVAE/ACVAE-PyTorch#2]
和2021年春季见到的序列论文比，这个文章很不错，如果效果真的如论文那么好的话，也算是一个巨大的突破了。交大的论文写的真的好高端，前几年的s3rec，还有这个。
如果把学习模块换成更先进的的模型，效果如何？
在大规模数据集合，表现如何？电影-10M数据集，为什么只有4.7M个records(论文的数据描述里)？

**Comment by xiez22** [comment]
您好！
	感谢对我们工作的认可。我们对movielens-10m数据集和其他数据集都进行了预处理，去除了交互较少的用户和交互较少的书籍（可以看实验部分数据处理的章节），这个也是推荐论文的一般做法。表格中展示的数据都是经过了预处理之后的数据。我们在github中的代码没有包括数据预处理的代码，我们之后可能会补上。如果您对论文还有任何其他疑问，欢迎发邮件询问。

	谢谢！


谢哲
***@***.***

**Comment by xiez22** [comment]
其它的模型我们暂时还没有尝试过。我们主要是针对z与x的序列依赖关系进行建模，所以使用了GRU-CNN的结构来做encoder。

**Comment by sizhongyibanhts** [comment]
嗯  明白老师  对您的工作非常感兴趣  后续如果我们这边有类似任务的话  我会在您的基础上尝试一下的发自我的荣耀手机-------- 原始邮件 --------发件人： Xie Zhe ***@***.***>日期： 2021年5月9日周日 19:01收件人： ACVAE/ACVAE-PyTorch ***@***.***>抄送： Han Tianshuo ***@***.***>, Author ***@***.***>主    题： Re: [ACVAE/ACVAE-PyTorch] 感觉很高端的工作 (#2)

其它的模型我们暂时还没有尝试过。我们主要是针对z与x的序列依赖关系进行建模，所以使用了GRU-CNN的结构来做encoder。
