### ISSUE TITLE
数据结果问题

### ISSUE THREAD

**Issue by liwenwei5110** [ACVAE/ACVAE-PyTorch#3]
请问作者你的对比实验是都自己复现跑的吗，我看了下bert4rec的结果在相同指标和数据集下与原论文差别很大，这是为什么呢

**Comment by xiez22** [comment]
你好，bert4rec的结果是我们自己跑的。原因是两个论文的评估指标不一样。bert4rec的数据划分方式是leave one out，我们的划分方式是4:1划分，二者划分方式不同就会导致结果有很大差异。
